<a href="https://colab.research.google.com/github/ZohrehBayramalizadeh/Neural-Networks/blob/main/PythonFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pyhton 

In [ ]:
list_1 = [ 1,2,3,4]
print(list_1)

[1, 2, 3, 4]


In [ ]:
len(list_1)

4

In [ ]:
list_1.__len__()

4

In [ ]:
list_2= ['red','blue', 'green']

In [ ]:
list_2.__len__()

3

In [ ]:
list_1.append(9.5)

In [ ]:
list_1

[1, 2, 3, 4, 9, 9.5]

In [ ]:
list_2.append('black')

In [ ]:
print(list_2)

['red', 'blue', 'green', 'black']


In [ ]:
list_2

['red', 'blue', 'green', 'black']

In [ ]:
list_1.extend([81,99,115])

In [ ]:
list_1

[1, 2, 3, 4, 9, 9.5, 81, 99, 115]

In [ ]:
list_1.extend(list_2)
print(list_1)

[1, 2, 3, 4, 9, 9.5, 81, 99, 115, 'red', 'blue', 'green', 'black']


In [ ]:
list_3 = [ 'hello', 22 , 37.9]
list_3 

['hello', 22, 37.9]

In [ ]:
list_name = [' ali', 'sara', 'bita', 'aydin']

In [ ]:
list_age = [22,25,26,24,29,22,24,22,26,28]

In [ ]:
list_age[3]

24

In [ ]:
list_2[0]

'red'

In [ ]:
list_age[3:6]

[26, 25, 24]

In [ ]:
list_age.count(22)

3

In [ ]:
list_age.sort()
print(list_age)

[22, 22, 22, 24, 24, 25, 26, 26, 28, 29]


In [ ]:
list_age.sort(reverse=True)
print(list_age)

[29, 28, 26, 26, 25, 24, 24, 22, 22, 22]


In [ ]:
list_name.clear()
print(list_name)

[]


In [ ]:
list_name = [' ali', 'sara', 'bita', 'aydin']

In [ ]:
list_name.pop(2)
print(list_name)

[' ali', 'sara', 'aydin']


In [ ]:
list_age.pop(2)
print(list_age)

[22, 25, 24, 29, 22, 24, 22, 26, 28]


In [ ]:
print(20+35)

55


In [ ]:
product = {
    'Iran' : 'Tehran',
    'color': 'red',
    'size': 'samll',
    'vol' : '200',
    'alizadeh': [20,18,17.5,19]    
}

In [ ]:
product['cost']= '1000'
print(product)

{'Iran': 'Tehran', 'color': 'red', 'size': 'samll', 'vol': '200', 'cost': '1000'}


In [ ]:
 a = product['color']
 print(a)

red


In [ ]:
 b = product['alizadeh']
 print(b)

[20, 18, 17.5, 19]


In [ ]:
product['alizadeh'] = [20,18,16,19]    

In [ ]:
print(product)

{'Iran': 'Tehran', 'color': 'red', 'size': 'samll', 'vol': '200', 'alizadeh': [20, 18, 16, 19]}


In [ ]:
print('ahmadi' in product)

False


In [ ]:
product_keys = product.keys()
print(product_keys)

dict_keys(['Iran', 'color', 'size', 'vol', 'alizadeh'])


# Numpy

np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [1]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [3]:
import numpy
import numpy as np

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [8]:
b = np.array([[1,5],[2,8],[3,9]])
print(b)

[[1 5]
 [2 8]
 [3 9]]


In [9]:
a.shape

(3,)

In [10]:
b.shape

(3, 2)

In [12]:
b[1,0]

2

In [14]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [17]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.full((8,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [20]:
np.multiply(2,8)

16

In [22]:
c = np.arange(6)
print(c)

[0 1 2 3 4 5]


In [23]:
c.shape

(6,)

In [24]:
c.dtype

dtype('int64')

In [25]:
print(c[0])

0


In [27]:
np.empty(2)

array([0.00000000e+000, 2.12199579e-314])

In [28]:
d = np.array([2,8,1,7,0,66,5,94,24])

In [29]:
np.sort(d)

array([ 0,  1,  2,  5,  7,  8, 24, 66, 94])

In [30]:
e = np.array([1, 2, 3, 4])
f = np.array([5, 6, 7, 8])

In [31]:
np.concatenate((e,f))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
g = np.array([[1, 2, 3, 4],[9,5,63,47]])
h = np.array([[5, 6, 7, 8]])

In [38]:
np.concatenate((g,h),axis=0)

array([[ 1,  2,  3,  4],
       [ 9,  5, 63, 47],
       [ 5,  6,  7,  8]])

In [39]:
g.ndim

2

In [40]:
g.size

8

In [41]:
g.shape

(2, 4)

In [44]:
i =  np.arange(10)
print(i)

[0 1 2 3 4 5 6 7 8 9]


In [46]:
r=i.reshape(5,2)
print(r)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Pandas

In [ ]:
!pip install pandas

In [47]:
import pandas as pd

In [49]:
s = pd.Series([1,3,5,np.nan,6,9,8])

In [50]:
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    9.0
6    8.0
dtype: float64
