<a href="https://colab.research.google.com/github/ZohrehBayramalizadeh/Neural-Networks/blob/main/PythonFromScratch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Pyhton 

In [ ]:
list_1 = [ 1,2,3,4]
print(list_1)

[1, 2, 3, 4]


In [ ]:
len(list_1)

4

In [ ]:
list_1.__len__()

4

In [ ]:
list_2= ['red','blue', 'green']

In [ ]:
list_2.__len__()

3

In [ ]:
list_1.append(9.5)

In [ ]:
list_1

[1, 2, 3, 4, 9, 9.5]

In [ ]:
list_2.append('black')

In [ ]:
print(list_2)

['red', 'blue', 'green', 'black']


In [ ]:
list_2

['red', 'blue', 'green', 'black']

In [ ]:
list_1.extend([81,99,115])

In [ ]:
list_1

[1, 2, 3, 4, 9, 9.5, 81, 99, 115]

In [ ]:
list_1.extend(list_2)
print(list_1)

[1, 2, 3, 4, 9, 9.5, 81, 99, 115, 'red', 'blue', 'green', 'black']


In [ ]:
list_3 = [ 'hello', 22 , 37.9]
list_3 

['hello', 22, 37.9]

In [ ]:
list_name = [' ali', 'sara', 'bita', 'aydin']

In [ ]:
list_age = [22,25,26,24,29,22,24,22,26,28]

In [ ]:
list_age[3]

24

In [ ]:
list_2[0]

'red'

In [ ]:
list_age[3:6]

[26, 25, 24]

In [ ]:
list_age.count(22)

3

In [ ]:
list_age.sort()
print(list_age)

[22, 22, 22, 24, 24, 25, 26, 26, 28, 29]


In [ ]:
list_age.sort(reverse=True)
print(list_age)

[29, 28, 26, 26, 25, 24, 24, 22, 22, 22]


In [ ]:
list_name.clear()
print(list_name)

[]


In [ ]:
list_name = [' ali', 'sara', 'bita', 'aydin']

In [ ]:
list_name.pop(2)
print(list_name)

[' ali', 'sara', 'aydin']


In [ ]:
list_age.pop(2)
print(list_age)

[22, 25, 24, 29, 22, 24, 22, 26, 28]


In [ ]:
print(20+35)

55


In [ ]:
product = {
    'Iran' : 'Tehran',
    'color': 'red',
    'size': 'samll',
    'vol' : '200',
    'alizadeh': [20,18,17.5,19]    
}

In [ ]:
product['cost']= '1000'
print(product)

{'Iran': 'Tehran', 'color': 'red', 'size': 'samll', 'vol': '200', 'cost': '1000'}


In [ ]:
 a = product['color']
 print(a)

red


In [ ]:
 b = product['alizadeh']
 print(b)

[20, 18, 17.5, 19]


In [ ]:
product['alizadeh'] = [20,18,16,19]    

In [ ]:
print(product)

{'Iran': 'Tehran', 'color': 'red', 'size': 'samll', 'vol': '200', 'alizadeh': [20, 18, 16, 19]}


In [ ]:
print('ahmadi' in product)

False


In [ ]:
product_keys = product.keys()
print(product_keys)

dict_keys(['Iran', 'color', 'size', 'vol', 'alizadeh'])


# Numpy

np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype

In [ ]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [5]:
import numpy
import numpy as np

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1,5],[2,8],[3,9]])
print(b)

[[1 5]
 [2 8]
 [3 9]]


In [ ]:
a.shape

(3,)

In [ ]:
b.shape

(3, 2)

In [ ]:
b[1,0]

2

In [ ]:
np.zeros((6,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [ ]:
np.ones((5,8))

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.full((8,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [ ]:
np.multiply(2,8)

16

In [ ]:
c = np.arange(6)
print(c)

[0 1 2 3 4 5]


In [ ]:
c.shape

(6,)

In [ ]:
c.dtype

dtype('int64')

In [ ]:
print(c[0])

0


In [ ]:
np.empty(2)

array([0.00000000e+000, 2.12199579e-314])

In [ ]:
d = np.array([2,8,1,7,0,66,5,94,24])

In [ ]:
np.sort(d)

array([ 0,  1,  2,  5,  7,  8, 24, 66, 94])

In [ ]:
e = np.array([1, 2, 3, 4])
f = np.array([5, 6, 7, 8])

In [ ]:
np.concatenate((e,f))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [ ]:
g = np.array([[1, 2, 3, 4],[9,5,63,47]])
h = np.array([[5, 6, 7, 8]])

In [ ]:
np.concatenate((g,h),axis=0)

array([[ 1,  2,  3,  4],
       [ 9,  5, 63, 47],
       [ 5,  6,  7,  8]])

In [ ]:
g.ndim

2

In [ ]:
g.size

8

In [ ]:
g.shape

(2, 4)

In [ ]:
i =  np.arange(10)
print(i)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
r=i.reshape(5,2)
print(r)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


# Pandas

In [ ]:
!pip install pandas

In [10]:
import pandas as pd

In [6]:
s = pd.Series([1,3,5,np.nan,6,9,8])

In [7]:
print(s)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    9.0
6    8.0
dtype: float64


In [29]:
df =pd.DataFrame(
    {
        "A":20.00,
        "date" : pd.Timestamp("20220102"),
        "exam" : np.array([3] * 4, dtype="int32"),
        "b":pd.Categorical(["test", "train", "test", "train"]),
        "F": "pass",

    }

)

In [30]:
df

A       date  exam      b     F
0  20.0 2022-01-02     3   test  pass
1  20.0 2022-01-02     3  train  pass
2  20.0 2022-01-02     3   test  pass
3  20.0 2022-01-02     3  train  pass

In [18]:
df.dtypes

A              float64
date    datetime64[ns]
exam             int32
b             category
F               object
dtype: object

In [19]:
df.head()

A       date  exam      b     F
0  20.0 2022-01-02     3   test  pass
1  20.0 2022-01-02     3  train  pass
2  20.0 2022-01-02     3   test  pass
3  20.0 2022-01-02     3  train  pass

In [20]:
df.tail(2)

A       date  exam      b     F
2  20.0 2022-01-02     3   test  pass
3  20.0 2022-01-02     3  train  pass

In [21]:
df.columns

Index(['A', 'date', 'exam', 'b', 'F'], dtype='object')

In [23]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [24]:
df.describe()

A  exam
count   4.0   4.0
mean   20.0   3.0
std     0.0   0.0
min    20.0   3.0
25%    20.0   3.0
50%    20.0   3.0
75%    20.0   3.0
max    20.0   3.0

In [25]:
df.T

0                    1                    2  \
A                    20.0                 20.0                 20.0   
date  2022-01-02 00:00:00  2022-01-02 00:00:00  2022-01-02 00:00:00   
exam                    3                    3                    3   
b                    test                train                 test   
F                    pass                 pass                 pass   

                        3  
A                    20.0  
date  2022-01-02 00:00:00  
exam                    3  
b                   train  
F                    pass

In [26]:
df.sort_index(axis=1, ascending=False)

exam       date      b     F     A
0     3 2022-01-02   test  pass  20.0
1     3 2022-01-02  train  pass  20.0
2     3 2022-01-02   test  pass  20.0
3     3 2022-01-02  train  pass  20.0

In [27]:
df.sort_values("date")

A       date  exam      b     F
0  20.0 2022-01-02     3   test  pass
1  20.0 2022-01-02     3  train  pass
2  20.0 2022-01-02     3   test  pass
3  20.0 2022-01-02     3  train  pass

In [33]:
df.iloc[3]

A                      20.0
date    2022-01-02 00:00:00
exam                      3
b                     train
F                      pass
Name: 3, dtype: object

In [34]:
df.iloc[1:3]

A       date  exam      b     F
1  20.0 2022-01-02     3  train  pass
2  20.0 2022-01-02     3   test  pass

In [36]:
df["A"]

0    20.0
1    20.0
2    20.0
3    20.0
Name: A, dtype: float64

In [37]:
df[0:3]

A       date  exam      b     F
0  20.0 2022-01-02     3   test  pass
1  20.0 2022-01-02     3  train  pass
2  20.0 2022-01-02     3   test  pass

In [42]:
df.loc[:,["A", "b"]]

A      b
0  20.0   test
1  20.0  train
2  20.0   test
3  20.0  train

In [43]:
df.loc["20220102":"20220104", ["A", "b"]]

Empty DataFrame
Columns: [A, b]
Index: []

# Matplotlib